// Generated by gencpp from file sewts_task/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SEWTS_TASK_MESSAGE_ADDTWOINTS_H
#define SEWTS_TASK_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <sewts_task/AddTwoIntsRequest.h>
#include <sewts_task/AddTwoIntsResponse.h>


namespace sewts_task
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace sewts_task


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sewts_task::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::sewts_task::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::sewts_task::AddTwoInts > {
  static const char* value()
  {
    return "sewts_task/AddTwoInts";
  }

  static const char* value(const ::sewts_task::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::sewts_task::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::sewts_task::AddTwoInts > 
template<>
struct MD5Sum< ::sewts_task::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sewts_task::AddTwoInts >::value();
  }
  static const char* value(const ::sewts_task::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sewts_task::AddTwoIntsRequest> should match 
// service_traits::DataType< ::sewts_task::AddTwoInts > 
template<>
struct DataType< ::sewts_task::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::sewts_task::AddTwoInts >::value();
  }
  static const char* value(const ::sewts_task::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sewts_task::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::sewts_task::AddTwoInts > 
template<>
struct MD5Sum< ::sewts_task::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sewts_task::AddTwoInts >::value();
  }
  static const char* value(const ::sewts_task::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sewts_task::AddTwoIntsResponse> should match 
// service_traits::DataType< ::sewts_task::AddTwoInts > 
template<>
struct DataType< ::sewts_task::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::sewts_task::AddTwoInts >::value();
  }
  static const char* value(const ::sewts_task::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEWTS_TASK_MESSAGE_ADDTWOINTS_H
